# Site settings
title: Broarm
email: contact@bram-de-leeuw.nl
description: Bram de Leeuw is an Graphic / Interactive designer.
baseurl: ""
url: "http://broarm.github.io"
twitter_username: bramdeleeuw
github_username:  TheBnl

# Build settings
markdown: kramdown
sass:
    style: :compressed
