# Site settings
title: Broarm
email: contact@bram-de-leeuw.nl
description: Bram de Leeuw is an Graphic / Interactive designer.
baseurl: ""
url: "http://broarm.nl"
twitter_username: bramdeleeuw
github_username:  TheBnl
permalink: /:title/
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Build settings
markdown: kramdown
sass:
    style: :compressed
